# Networking
terraform state mv 'data.aws_availability_zones.available' 'module.networking.data.aws_availability_zones.available'
terraform state mv 'aws_vpc.main' 'module.networking.aws_vpc.main'
terraform state mv 'aws_internet_gateway.main' 'module.networking.aws_internet_gateway.main'
terraform state mv 'aws_subnet.public[0]' 'module.networking.aws_subnet.public[0]'
terraform state mv 'aws_subnet.public[1]' 'module.networking.aws_subnet.public[1]'
terraform state mv 'aws_subnet.private_app[0]' 'module.networking.aws_subnet.private_app[0]'
terraform state mv 'aws_subnet.private_app[1]' 'module.networking.aws_subnet.private_app[1]'
terraform state mv 'aws_subnet.private_data[0]' 'module.networking.aws_subnet.private_data[0]'
terraform state mv 'aws_subnet.private_data[1]' 'module.networking.aws_subnet.private_data[1]'
terraform state mv 'aws_eip.nat' 'module.networking.aws_eip.nat'
terraform state mv 'aws_nat_gateway.main' 'module.networking.aws_nat_gateway.main'
terraform state mv 'aws_route_table.public' 'module.networking.aws_route_table.public'
terraform state mv 'aws_route_table.private_app' 'module.networking.aws_route_table.private_app'
terraform state mv 'aws_route_table.private_data' 'module.networking.aws_route_table.private_data'
terraform state mv 'aws_route_table_association.public[0]' 'module.networking.aws_route_table_association.public[0]'
terraform state mv 'aws_route_table_association.public[1]' 'module.networking.aws_route_table_association.public[1]'
terraform state mv 'aws_route_table_association.private_app[0]' 'module.networking.aws_route_table_association.private_app[0]'
terraform state mv 'aws_route_table_association.private_app[1]' 'module.networking.aws_route_table_association.private_app[1]'
terraform state mv 'aws_route_table_association.private_data[0]' 'module.networking.aws_route_table_association.private_data[0]'
terraform state mv 'aws_route_table_association.private_data[1]' 'module.networking.aws_route_table_association.private_data[1]'

# Security
terraform state mv 'aws_security_group.alb' 'module.security.aws_security_group.alb'
terraform state mv 'aws_security_group.app' 'module.security.aws_security_group.app'
terraform state mv 'aws_security_group.rds' 'module.security.aws_security_group.rds'
terraform state mv 'aws_vpc_security_group_ingress_rule.alb_http' 'module.security.aws_vpc_security_group_ingress_rule.alb_http'
terraform state mv 'aws_vpc_security_group_ingress_rule.alb_https' 'module.security.aws_vpc_security_group_ingress_rule.alb_https'
terraform state mv 'aws_vpc_security_group_egress_rule.alb_all_out' 'module.security.aws_vpc_security_group_egress_rule.alb_all_out'
terraform state mv 'aws_vpc_security_group_ingress_rule.app_from_alb' 'module.security.aws_vpc_security_group_ingress_rule.app_from_alb'
terraform state mv 'aws_vpc_security_group_egress_rule.app_to_rds' 'module.security.aws_vpc_security_group_egress_rule.app_to_rds'
terraform state mv 'aws_vpc_security_group_egress_rule.app_https_out' 'module.security.aws_vpc_security_group_egress_rule.app_https_out'
terraform state mv 'aws_vpc_security_group_egress_rule.app_dns_udp' 'module.security.aws_vpc_security_group_egress_rule.app_dns_udp'
terraform state mv 'aws_vpc_security_group_egress_rule.app_dns_tcp' 'module.security.aws_vpc_security_group_egress_rule.app_dns_tcp'
terraform state mv 'aws_vpc_security_group_ingress_rule.rds_from_app' 'module.security.aws_vpc_security_group_ingress_rule.rds_from_app'
terraform state mv 'aws_vpc_security_group_egress_rule.rds_all_out' 'module.security.aws_vpc_security_group_egress_rule.rds_all_out'

# Database
terraform state mv 'aws_db_subnet_group.main' 'module.database.aws_db_subnet_group.main'
terraform state mv 'random_password.db_password' 'module.database.random_password.db_password'
terraform state mv 'aws_db_instance.main' 'module.database.aws_db_instance.main'
terraform state mv 'aws_secretsmanager_secret.db_credentials' 'module.database.aws_secretsmanager_secret.db_credentials'
terraform state mv 'random_password.webui_secret_key' 'module.database.random_password.webui_secret_key'
terraform state mv 'aws_secretsmanager_secret_version.db_credentials' 'module.database.aws_secretsmanager_secret_version.db_credentials'

# IAM - CI/CD roles
terraform state mv 'data.aws_caller_identity.current' 'module.iam.data.aws_caller_identity.current'
terraform state mv 'aws_iam_role.codebuild' 'module.iam.aws_iam_role.codebuild'
terraform state mv 'aws_iam_role_policy.codebuild' 'module.iam.aws_iam_role_policy.codebuild'
terraform state mv 'aws_iam_role.codepipeline' 'module.iam.aws_iam_role.codepipeline'
terraform state mv 'aws_iam_role_policy.codepipeline' 'module.iam.aws_iam_role_policy.codepipeline'
terraform state mv 'aws_iam_role.codedeploy' 'module.iam.aws_iam_role.codedeploy'
terraform state mv 'aws_iam_role_policy_attachment.codedeploy' 'module.iam.aws_iam_role_policy_attachment.codedeploy'
terraform state mv 'aws_iam_role_policy.codedeploy_extra' 'module.iam.aws_iam_role_policy.codedeploy_extra'

# IAM - ECS roles
terraform state mv 'aws_iam_role.ecs_task_execution' 'module.iam.aws_iam_role.ecs_task_execution'
terraform state mv 'aws_iam_role_policy_attachment.ecs_task_execution' 'module.iam.aws_iam_role_policy_attachment.ecs_task_execution'
terraform state mv 'aws_iam_role_policy.ecs_execution_secrets' 'module.iam.aws_iam_role_policy.ecs_execution_secrets'
terraform state mv 'aws_iam_role.ecs_task' 'module.iam.aws_iam_role.ecs_task'
terraform state mv 'aws_iam_role_policy.ecs_task' 'module.iam.aws_iam_role_policy.ecs_task'

# ECR
terraform state mv 'aws_ecr_repository.ollama' 'module.ecr.aws_ecr_repository.ollama'
terraform state mv 'aws_ecr_lifecycle_policy.ollama' 'module.ecr.aws_ecr_lifecycle_policy.ollama'

# ECS + ALB
terraform state mv 'aws_ecs_cluster.main' 'module.ecs.aws_ecs_cluster.main'
terraform state mv 'aws_cloudwatch_log_group.openwebui' 'module.ecs.aws_cloudwatch_log_group.openwebui'
terraform state mv 'aws_cloudwatch_log_group.ollama' 'module.ecs.aws_cloudwatch_log_group.ollama'
terraform state mv 'aws_ecs_task_definition.app' 'module.ecs.aws_ecs_task_definition.app'
terraform state mv 'aws_ecs_service.app' 'module.ecs.aws_ecs_service.app'
terraform state mv 'aws_lb.main' 'module.ecs.aws_lb.main'
terraform state mv 'aws_lb_target_group.openwebui' 'module.ecs.aws_lb_target_group.openwebui'
terraform state mv 'aws_lb_listener.http' 'module.ecs.aws_lb_listener.http'
