version: 0.2

env:
  variables:
    TF_VAR_deploy_cicd: "true"
    TF_VAR_deploy_lambda: "true"
    TF_VAR_ecs_desired_count: "2"
    TF_VAR_ecs_max_count: "4"
    TF_VAR_github_owner: "RichyCey"
    TF_VAR_github_repo: "AWS-education"
    TF_VAR_github_branch: "master"

phases:
  install:
    commands:
      - wget -q https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip
      - unzip -o terraform_1.9.8_linux_amd64.zip -d /usr/local/bin/
      - terraform --version
      - pip install psycopg2-binary -t lambda/layer/python --quiet
      - cd lambda/layer && zip -r ../psycopg2_layer.zip python -x '*.pyc' && cd ../..
  pre_build:
    commands:
      - terraform fmt -check -recursive
  build:
    commands:
      - terraform init -input=false
      - terraform validate
      - terraform plan -input=false -no-color
